debug: true
record_log: true
wallet:
  hotkey: default
  name: default
  path: ~/.bittensor/wallets/
axon:
  max_gradients: 100
  max_workers: 10
  use_upnpc: false
metagraph:
  stale_emit_filter: -1
neuron:
  modality: 0
nucleus:
  max_workers: 5
  queue_maxsize: 1000
  queue_timeout: 5
receptor:
  do_backoff: true
  max_backoff: 100
  pass_gradients: true
  timeout: 3
router:
  key_dim: 100
  stale_emit_filter: 10000
  topk: 10
subtensor:
  chain_endpoint: null
  network: kusanagi